// data.js — Data film contoh (demo). Poster & banner disimpan lokal di folder images/.
// Ganti "video" dengan aset asli kamu nanti, dan ganti file di images/posters & images/banners sesuai kebutuhan.
const MOVIES = [
  {
    id: "vifan",
    title: "Viva Fantasy The Movie",
    year: 2022,
    genre: "Animasi",
    rating: "SU",
    duration: "81 mnt",
    description: "Fifteen years after the desperate sealing ritual that claims the lives of Spade and Heart, three siblings: Marvel, Samsul, and Peppey embark on a journey into the forbidden lands of Vermilion. Marvel's mystical green pendant awakens dark powers and attracts Herobrine's sinister attention.",
    poster: "postervifan.jpg",
    banner: "vifan.jpg",
    youtubeId: "90aPTVtg0pI?si=7fd8GsV_HiRtoDfr",
    subtitle: "subtitles/sample-id.vtt",
    category: "Animasi"
  },
  {
    id: "bbb",
    title: "Big Buck Bunny",
    year: 2008,
    genre: "Animasi",
    rating: "SU",
    duration: "10 mnt",
    description: "Seekor kelinci raksasa yang baik hati dibalas dengan kejahilan oleh tiga hewan pengerat nakal. Suatu hari, kesabarannya habis dan ia membalas dengan caranya sendiri.",
    poster: "images/posters/bbb.jpg",
    banner: "images/banners/bbb.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Trending Sekarang"
  },
  {
    id: "elephant",
    title: "Elephant's Dream",
    year: 2006,
    genre: "Fantasi",
    rating: "13+",
    duration: "11 mnt",
    description: "Dua karakter menjelajahi dunia mesin surreal yang penuh keanehan visual dan makna tersembunyi di setiap sudutnya.",
    poster: "images/posters/elephant.jpg",
    banner: "images/banners/elephant.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Trending Sekarang"
  },
  {
    id: "sintel",
    title: "Sintel",
    year: 2010,
    genre: "Petualangan",
    rating: "13+",
    duration: "15 mnt",
    description: "Seorang gadis muda bernama Sintel berpetualang mencari naga muda yang telah membesarkannya dan hilang secara misterius.",
    poster: "images/posters/sintel.jpg",
    banner: "images/banners/sintel.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Film Populer"
  },
  {
    id: "tears",
    title: "Tears of Steel",
    year: 2012,
    genre: "Sci-Fi",
    rating: "17+",
    duration: "12 mnt",
    description: "Sekelompok prajurit dan ilmuwan berkumpul di reruntuhan Amsterdam untuk menyusun rencana terakhir melawan pasukan robot yang mengancam bumi.",
    poster: "images/posters/tears.jpg",
    banner: "images/banners/tears.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Film Populer"
  },
  {
    id: "blazes",
    title: "For Bigger Blazes",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Aksi seru penuh kobaran api dan kecepatan tinggi dalam tayangan singkat yang memacu adrenalin.",
    poster: "images/posters/blazes.jpg",
    banner: "images/banners/blazes.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "escape",
    title: "For Bigger Escape",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Pelarian penuh ketegangan lintas medan ekstrem dengan visual sinematik yang memukau.",
    poster: "images/posters/escape.jpg",
    banner: "images/banners/escape.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscape.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "fun",
    title: "For Bigger Fun",
    year: 2015,
    genre: "Komedi",
    rating: "SU",
    duration: "1 mnt",
    description: "Tayangan ringan penuh keseruan yang cocok ditonton bersama keluarga di akhir pekan.",
    poster: "images/posters/fun.jpg",
    banner: "images/banners/fun.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Komedi"
  },
  {
    id: "joyrides",
    title: "For Bigger Joyrides",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Perjalanan liar penuh kejutan dan kecepatan yang akan memacu jantungmu berdegup kencang.",
    poster: "images/posters/joyrides.jpg",
    banner: "images/banners/joyrides.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "meltdowns",
    title: "For Bigger Meltdowns",
    year: 2015,
    genre: "Thriller",
    rating: "17+",
    duration: "1 mnt",
    description: "Ketegangan memuncak dalam tayangan singkat penuh kejutan dari awal hingga akhir.",
    poster: "images/posters/meltdowns.jpg",
    banner: "images/banners/meltdowns.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Thriller"
  },
  {
    id: "rmci2024",
    title: "Rewind Minecraft Indonesia 2024",
    year: 2024,
    genre: "Animasi, Slice Of Life, Emotional",
    rating: "SU",
    duration: "30 mnt",
    description: "Alisha adalah seorang Gen-Z yang sedang tinggal bersama Kakek, Nenek, dan adiknya Mahesa di sebuah Desa. Alisha harus dihadapkan dengan kenyataan bahwa dirinya berada di dunia antara kehidupan atau kematian, akibat terjatuh dari dari atas kursi saat sedang mengambil buku di rak yang tinggi. Ia harus memilih apakah harus kembali ke tubuhnya atau pergi ke alam akhirat.",
    poster: "rmci2024p.jpg",
    banner: "rmcib2024.jpg",
    video: "https://gdurl.com/W8TK",
    subtitle: "subtitles/rmci2024.vtt",
    category: "Animasi"
  },
  {
    id: "ava",
    title: "Animation Vs Animator Full Episode",
    year: 2005,
    genre: "Animasi, Action",
    rating: "SU",
    duration: "5 JAM",
    description: "Seorang animator menghadapi animasi miliknya sendiri dalam pertarungan yang mematikan. Medan perang? Antarmuka Flash itu sendiri. Sesosok stick figure dibuat oleh seorang animator dengan maksud untuk menyiksa. Stick figure itu akan menggunakan semua yang dapat ditemukannya - alat kuas, alat penghapus, dll. - untuk membalas penyiksanya. Ini adalah akal melawan kekuatan. Siapa yang akan menang? Kalian dapat mencari tahu sendiri.",
    poster: "ava.png",
    banner: "avab.jpg",
    video: "#",
    subtitle: "subtitles/ava.vtt",
    category: "Animasi"
  }
];
