// data.js — Data film contoh (demo). Ganti "video" & "poster" dengan aset asli kamu nanti.
const MOVIES = [
  {
    id: "vifan",
    title: "Viva Fantasy The Movie",
    year: 2022,
    genre: "Animasi",
    rating: "SU",
    duration: "81 mnt",
    description: "Fifteen years after the desperate sealing ritual that claims the lives of Spade and Heart, three siblings: Marvel, Samsul, and Peppey embark on a journey into the forbidden lands of Vermilion. Marvel's mystical green pendant awakens dark powers and attracts Herobrine's sinister attention.",
    poster: "postervifan.jpg",
    banner: "vifan.jpg",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Animasi"
  },
  {
    id: "elephant",
    title: "Elephant's Dream",
    year: 2006,
    genre: "Fantasi",
    rating: "13+",
    duration: "11 mnt",
    description: "Dua karakter menjelajahi dunia mesin surreal yang penuh keanehan visual dan makna tersembunyi di setiap sudutnya.",
    poster: "https://placehold.co/400x600/104a2b/ffffff?text=Elephant%27s+Dream",
    banner: "https://placehold.co/1200x500/104a2b/ffffff?text=Elephant%27s+Dream",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Trending Sekarang"
  },
  {
    id: "sintel",
    title: "Sintel",
    year: 2010,
    genre: "Petualangan",
    rating: "13+",
    duration: "15 mnt",
    description: "Seorang gadis muda bernama Sintel berpetualang mencari naga muda yang telah membesarkannya dan hilang secara misterius.",
    poster: "https://placehold.co/400x600/0e5c34/ffffff?text=Sintel",
    banner: "https://placehold.co/1200x500/0e5c34/ffffff?text=Sintel",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Film Populer"
  },
  {
    id: "tears",
    title: "Tears of Steel",
    year: 2012,
    genre: "Sci-Fi",
    rating: "17+",
    duration: "12 mnt",
    description: "Sekelompok prajurit dan ilmuwan berkumpul di reruntuhan Amsterdam untuk menyusun rencana terakhir melawan pasukan robot yang mengancam bumi.",
    poster: "https://placehold.co/400x600/065f46/ffffff?text=Tears+of+Steel",
    banner: "https://placehold.co/1200x500/065f46/ffffff?text=Tears+of+Steel",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Film Populer"
  },
  {
    id: "blazes",
    title: "For Bigger Blazes",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Aksi seru penuh kobaran api dan kecepatan tinggi dalam tayangan singkat yang memacu adrenalin.",
    poster: "https://placehold.co/400x600/166534/ffffff?text=Bigger+Blazes",
    banner: "https://placehold.co/1200x500/166534/ffffff?text=Bigger+Blazes",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "escape",
    title: "For Bigger Escape",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Pelarian penuh ketegangan lintas medan ekstrem dengan visual sinematik yang memukau.",
    poster: "https://placehold.co/400x600/15803d/ffffff?text=Bigger+Escape",
    banner: "https://placehold.co/1200x500/15803d/ffffff?text=Bigger+Escape",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscape.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "fun",
    title: "For Bigger Fun",
    year: 2015,
    genre: "Komedi",
    rating: "SU",
    duration: "1 mnt",
    description: "Tayangan ringan penuh keseruan yang cocok ditonton bersama keluarga di akhir pekan.",
    poster: "https://placehold.co/400x600/16a34a/ffffff?text=Bigger+Fun",
    banner: "https://placehold.co/1200x500/16a34a/ffffff?text=Bigger+Fun",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Komedi"
  },
  {
    id: "joyrides",
    title: "For Bigger Joyrides",
    year: 2015,
    genre: "Aksi",
    rating: "13+",
    duration: "1 mnt",
    description: "Perjalanan liar penuh kejutan dan kecepatan yang akan memacu jantungmu berdegup kencang.",
    poster: "https://placehold.co/400x600/22c55e/052e16?text=Bigger+Joyrides",
    banner: "https://placehold.co/1200x500/22c55e/052e16?text=Bigger+Joyrides",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Aksi & Laga"
  },
  {
    id: "meltdowns",
    title: "For Bigger Meltdowns",
    year: 2015,
    genre: "Thriller",
    rating: "17+",
    duration: "1 mnt",
    description: "Ketegangan memuncak dalam tayangan singkat penuh kejutan dari awal hingga akhir.",
    poster: "https://placehold.co/400x600/059669/ffffff?text=Bigger+Meltdowns",
    banner: "https://placehold.co/1200x500/059669/ffffff?text=Bigger+Meltdowns",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    subtitle: "subtitles/sample-id.vtt",
    category: "Thriller"
  },
  {
    id: "rmci2025",
    title: "Rewind Minecraft Indonesia 2025",
    year: 2025,
    genre: "Animasi, Fantasy, Action",
    rating: "SU",
    duration: "40 mnt",
    description: "Rewind Minecraft 2025 Sinopsis mengisahkan petualangan Mark, Freya, dan Benny di 2026. Mereka akan melanjutkan kisah yang telah dimulai di 2025 dengan berbagai tantangan dan keajaiban yang mereka temukan.",
    poster: "https://placehold.co/400x600/047857/ffffff?text=On+Street+%26+Dirt",
    banner: "rmcib2025.jpg",
    video: "https://gdurl.com/W8TK",
    subtitle: "subtitles/rmci2025.vtt",
    category: "Animasi"
  }
];
